site_name: hope's blog
theme: 'material'
dev_addr: '127.0.0.1:8888'

nav:
  - 首页: index.md
  - 常见配置:
    - 搬瓦工配置: cfg/bwgconfig.md
    - Markdown语法: cfg/Markdown基本语法.md
  - 书籍: 
    - 代码整洁之道: book/代码整洁之道.md
    - 代码相关书籍: book/代码相关书籍.md



